const init = () => {
  console.log("DY| Running custom evaluator test.");
};

try {
  init();
} catch (e) {
  console.log("DY | error", e);
}
